### ISSUE TITLE
Branch is forked from inital default branch, not last

### ISSUE THREAD

**Issue by PurpleBooth** [PurpleBooth/change-github-default-branch.sh#1]
Reported by @greg-1-anderson

```
 json.load(sys.stdin)[0]["object"]["sha"] returns the sha for the first branch from git/refs/heads, which might not necessarily be the current default branch.
```

**Comment by Lewiscowles1986** [comment]
Can you sort or filter so the only branch left is a default branch?

**Comment by Lewiscowles1986** [comment]
Can you sort or filter so the only branch left is a default branch?

I just checked and you can `GET` `https://api.github.com/repos/$REPO` and use jq to get the current default_branch, then GET `https://api.github.com/repos/$REPO/git/refs/heads/$DEFAULT_BRANCH` and you'll only have the object sha for the default branch

PR inbound
