### ISSUE TITLE
GITHUB_TOKEN positional or from ENV?

### ISSUE THREAD

**Issue by Lewiscowles1986** [PurpleBooth/change-github-default-branch.sh#3]
When I use a windows PC I often run a VM with `GITHUB_TOKEN` set in the environment. This saves me moving private keys around.

- As a user with an environment that already has a `GITHUB_TOKEN` accessible to the script
- It would *be nice to not need to enter it via command line*
- So that information available is used, minimizing operator involvement

Maybe this isn't needed, but it would save me sending "$GITHUB_TOKEN" as an argument for it to be called GITHUB_TOKEN within the script.

**Comment by PurpleBooth** [comment]
I also do this exact thing, this is a great idea
